### ISSUE TITLE
Support multi-channel ABFs

### ISSUE THREAD

**Issue by rjlopez2** [swharden/AbfConvert#1]
Dear @swharden 

thanks a lot for your program, really nice.

We have a set of .abf files that display both recorded signals as well as our voltage protocol. When we use your program by just dragging and dropping our files we unfortunately only can see the traces from the recording but not the protocol. The generated csv file only display the time and the sweeps but not the protocol.

We have been looking at the documentation but could not find anything how we could also extract the data from the protocol we apply. Is there any way to extract as well the protocol trace from our files?

if you need to look at one example I can provide you a file.

We are using Clampfit version 11.1.0.23

Best

**Comment by swharden** [comment]
Hi @rjlopez2, github lets you add files <10MB directly in this comments box. Is that enough for you to share a sample ABF?

When you say "voltage protocol", do you mean a trace that you normally have to _generate_ using clampfit by clicking "edit" and "create stimulus waveform signal"? If this is the case, one solution may be to use ClampFit to generate the signal, then save the result as a new ABF. It's a little hacky, but it could get the job done in a pinch.

Note that there's also pyabf which can create stimulus waveform signals programmatically

**Comment by rjlopez2** [comment]
Hi @swharden,

> github lets you add files <10MB directly in this comments box. Is that enough for you to share a sample ABF?

indeed I wanted to upload right the way an example file but git-hub didn't like it the .abf format. I changed the file extension to .txt but this is in fact a .abf file. Just change it back to .abf and give it a go.

> When you say "voltage protocol", do you mean a trace that you normally have to generate using clampfit by clicking "edit" and "create stimulus waveform signal"?

I assume this is the case, but I can confirm this later with the persons that did the experiment.

> one solution may be to use ClampFit to generate the signal, then save the result as a new ABF. It's a little hacky, but it could get the job done in a pinch.

yes, we came up with this idea as well, however since we have large number of recording we would like to avoid to have to go one by one and try to do it programmatically when possible.

> Note that there's also pyabf which can create stimulus waveform signals programmatically

yes thanks!
I noted this after I formulate the issue here, but I will definitely have a look at it.

thanks a lot in advance.

Ruben

[2022_08_12_0006.txt](https://github.com/swharden/AbfConvert/files/9690183/2022_08_12_0006.txt)

**Comment by swharden** [comment]
Re-stating the feature suggestion: AbfConvert currently only outputs the first ADC channel in the ABF. The program could be extended to export all channels, solving the issue originally described here. 

The code that controls which channel is exported is here:

https://github.com/swharden/AbfConvert/blob/027a2395f988c17f09e1fc4c6981760b27774757/src/AbfConvert.GUI/Form1.cs#L63-L66

`abf.GetSweep()` has an optional argument to indicate which channel is to be exported.

**Comment by rjlopez2** [comment]
Hey @swharden 

Thanks for clarifying the issue here.

Btw I manage tho use the pyabf API and it's no just super well documented and straight forward to use but also super complete. It allows me to extract the two channels in the record. Probably this was also part of the information I was confused: there is indeed two channels containing data: one with the reading from the experiment (pAmp) and the other one is having what we called earlier the "voltage protocol" (mV).

In the mean time I will stick to the pyabf API because is solving our program and because even if I would like to make a contribution to implement this  feature,  unfortunately I am not literate with the language this app was build with (I believe C#)

Thanks again for your feedback and fast response and for helping me to understand/ learn what was happening here -newby here :) 


Cheers

Ruben

**Comment by swharden** [comment]
Hi @rjlopez2, sorry it took so long to get to this.

I added an option to set the channel when exporting. You can download the new version 1.2 from the website. Let me know if this doesn't do the trick! https://swharden.com/software/AbfConvert/

![image](https://user-images.githubusercontent.com/4165489/195965776-43f40fb2-7d3a-4232-95eb-54fe58628ceb.png)
